version: '3'
services:

  db-postgresql:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=shop
    ports:
      - 5432:5432

  db-redis:
    image: redis
    restart: always
    ports:
      - 6379:6379